import Head from "next/head";
import { SubscriptionList, AddEditTag, AddEditCreditCard } from "components";
import { useAuth } from "hooks";

const Subscrib = () => {
  const { user } = useAuth();

  return (
    <>
      <Head>
        <title>Subscrib.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? (
        <>
          <SubscriptionList />
          <AddEditCreditCard />
          <AddEditTag />
        </>
      ) : (
        "Login to see your dashboard"
      )}
    </>
  );
};

export default Subscrib;
