import Head from "next/head";
import { useMutation, useQuery } from "@apollo/client";
import { GET_TAGS } from "graphql/queries";
// import {  } from "graphql/mutations";
import { useAuth } from "hooks";

const Subscrib = () => {
  const { user } = useAuth();

  const { loading, error, data } = useQuery(GET_TAGS, { skip: !user });

  return (
    <>
      <Head>
        <title>Subscrib.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <pre>{JSON.stringify({ loading, error, data }, null, 2)}</pre>
    </>
  );
};

export default Subscrib;
